apiVersion: apps/v1
kind: Deployment
metadata:
  name: springjpa
  labels:
    app: springjpa
spec:
  selector:
    matchLabels:
      app: springjpa
  template:
    metadata:
      labels:
        app: springjpa
    spec:
      containers:
        - name: springjpa
          image: __IMAGE__@__DIGEST__
          ports:
            - name: http-server
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springjpa
  labels:
    app: springjpa
spec:
  ports:
    - port: 8080
      targetPort: http-server
  selector:
    app: springjpa
  type: NodePort
---
apiVersion: v1
kind: Route
metadata:
  name: springjpa
  labels:
    app: springjpa
spec:
  port:
    targetPort: 10000-tcp
  to:
    kind: Service
    name: springjpa
    weight: 100